language: node_js
node_js:
  - "6"
branches:
  only:
    - master
    - dev
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install: cd urlstream
script: npm test
